server:
  port: 8080
  
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
#    driver-class-name: ${DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}
  jpa:
    show-sql: true
    hibernate:
      ddl: ${JPA_DDL:update}
      ddl-auto: ${JPA_DDL_AUTO:update}
  main:
    allow-circular-references: true
  